version: '3.8'

services:
  nextjs:
    image: node:22-alpine
    container_name: nextjs-dev
    working_dir: /app
    volumes:
      - ./app:/app   # Monta toda a pasta do projeto
      - /app/node_modules   # Volume isolado para node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm install && npm run dev"]  # Instala dependências antes de rodar o Next.js
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
